/// The 66 books of the Protestant canon with their chapter counts.
///
/// Static data: the app ships this table and generates every reading plan
/// from it. Bible text is deliberately absent in v1; when it arrives it hangs
/// off [BibleBook.id] and [ChapterReference] without touching this file.
library;

enum Testament {
  old('Old Testament'),
  newT('New Testament');

  const Testament(this.title);
  final String title;
}

class BibleBook {
  const BibleBook({
    required this.id,
    required this.name,
    required this.abbreviation,
    required this.testament,
    required this.chapters,
    required this.order,
  });

  /// Stable key used in storage. Never rename.
  final String id;
  final String name;
  final String abbreviation;
  final Testament testament;
  final int chapters;

  /// 0-based canonical position, Genesis = 0, Revelation = 65.
  final int order;
}

const List<BibleBook> kBibleBooks = [
  BibleBook(
    id: 'genesis',
    name: 'Genesis',
    abbreviation: 'Gen',
    testament: Testament.old,
    chapters: 50,
    order: 0,
  ),
  BibleBook(
    id: 'exodus',
    name: 'Exodus',
    abbreviation: 'Exod',
    testament: Testament.old,
    chapters: 40,
    order: 1,
  ),
  BibleBook(
    id: 'leviticus',
    name: 'Leviticus',
    abbreviation: 'Lev',
    testament: Testament.old,
    chapters: 27,
    order: 2,
  ),
  BibleBook(
    id: 'numbers',
    name: 'Numbers',
    abbreviation: 'Num',
    testament: Testament.old,
    chapters: 36,
    order: 3,
  ),
  BibleBook(
    id: 'deuteronomy',
    name: 'Deuteronomy',
    abbreviation: 'Deut',
    testament: Testament.old,
    chapters: 34,
    order: 4,
  ),
  BibleBook(
    id: 'joshua',
    name: 'Joshua',
    abbreviation: 'Josh',
    testament: Testament.old,
    chapters: 24,
    order: 5,
  ),
  BibleBook(
    id: 'judges',
    name: 'Judges',
    abbreviation: 'Judg',
    testament: Testament.old,
    chapters: 21,
    order: 6,
  ),
  BibleBook(
    id: 'ruth',
    name: 'Ruth',
    abbreviation: 'Ruth',
    testament: Testament.old,
    chapters: 4,
    order: 7,
  ),
  BibleBook(
    id: '1_samuel',
    name: '1 Samuel',
    abbreviation: '1 Sam',
    testament: Testament.old,
    chapters: 31,
    order: 8,
  ),
  BibleBook(
    id: '2_samuel',
    name: '2 Samuel',
    abbreviation: '2 Sam',
    testament: Testament.old,
    chapters: 24,
    order: 9,
  ),
  BibleBook(
    id: '1_kings',
    name: '1 Kings',
    abbreviation: '1 Kgs',
    testament: Testament.old,
    chapters: 22,
    order: 10,
  ),
  BibleBook(
    id: '2_kings',
    name: '2 Kings',
    abbreviation: '2 Kgs',
    testament: Testament.old,
    chapters: 25,
    order: 11,
  ),
  BibleBook(
    id: '1_chronicles',
    name: '1 Chronicles',
    abbreviation: '1 Chr',
    testament: Testament.old,
    chapters: 29,
    order: 12,
  ),
  BibleBook(
    id: '2_chronicles',
    name: '2 Chronicles',
    abbreviation: '2 Chr',
    testament: Testament.old,
    chapters: 36,
    order: 13,
  ),
  BibleBook(
    id: 'ezra',
    name: 'Ezra',
    abbreviation: 'Ezra',
    testament: Testament.old,
    chapters: 10,
    order: 14,
  ),
  BibleBook(
    id: 'nehemiah',
    name: 'Nehemiah',
    abbreviation: 'Neh',
    testament: Testament.old,
    chapters: 13,
    order: 15,
  ),
  BibleBook(
    id: 'esther',
    name: 'Esther',
    abbreviation: 'Esth',
    testament: Testament.old,
    chapters: 10,
    order: 16,
  ),
  BibleBook(
    id: 'job',
    name: 'Job',
    abbreviation: 'Job',
    testament: Testament.old,
    chapters: 42,
    order: 17,
  ),
  BibleBook(
    id: 'psalms',
    name: 'Psalms',
    abbreviation: 'Ps',
    testament: Testament.old,
    chapters: 150,
    order: 18,
  ),
  BibleBook(
    id: 'proverbs',
    name: 'Proverbs',
    abbreviation: 'Prov',
    testament: Testament.old,
    chapters: 31,
    order: 19,
  ),
  BibleBook(
    id: 'ecclesiastes',
    name: 'Ecclesiastes',
    abbreviation: 'Eccl',
    testament: Testament.old,
    chapters: 12,
    order: 20,
  ),
  BibleBook(
    id: 'song_of_solomon',
    name: 'Song of Solomon',
    abbreviation: 'Song',
    testament: Testament.old,
    chapters: 8,
    order: 21,
  ),
  BibleBook(
    id: 'isaiah',
    name: 'Isaiah',
    abbreviation: 'Isa',
    testament: Testament.old,
    chapters: 66,
    order: 22,
  ),
  BibleBook(
    id: 'jeremiah',
    name: 'Jeremiah',
    abbreviation: 'Jer',
    testament: Testament.old,
    chapters: 52,
    order: 23,
  ),
  BibleBook(
    id: 'lamentations',
    name: 'Lamentations',
    abbreviation: 'Lam',
    testament: Testament.old,
    chapters: 5,
    order: 24,
  ),
  BibleBook(
    id: 'ezekiel',
    name: 'Ezekiel',
    abbreviation: 'Ezek',
    testament: Testament.old,
    chapters: 48,
    order: 25,
  ),
  BibleBook(
    id: 'daniel',
    name: 'Daniel',
    abbreviation: 'Dan',
    testament: Testament.old,
    chapters: 12,
    order: 26,
  ),
  BibleBook(
    id: 'hosea',
    name: 'Hosea',
    abbreviation: 'Hos',
    testament: Testament.old,
    chapters: 14,
    order: 27,
  ),
  BibleBook(
    id: 'joel',
    name: 'Joel',
    abbreviation: 'Joel',
    testament: Testament.old,
    chapters: 3,
    order: 28,
  ),
  BibleBook(
    id: 'amos',
    name: 'Amos',
    abbreviation: 'Amos',
    testament: Testament.old,
    chapters: 9,
    order: 29,
  ),
  BibleBook(
    id: 'obadiah',
    name: 'Obadiah',
    abbreviation: 'Obad',
    testament: Testament.old,
    chapters: 1,
    order: 30,
  ),
  BibleBook(
    id: 'jonah',
    name: 'Jonah',
    abbreviation: 'Jonah',
    testament: Testament.old,
    chapters: 4,
    order: 31,
  ),
  BibleBook(
    id: 'micah',
    name: 'Micah',
    abbreviation: 'Mic',
    testament: Testament.old,
    chapters: 7,
    order: 32,
  ),
  BibleBook(
    id: 'nahum',
    name: 'Nahum',
    abbreviation: 'Nah',
    testament: Testament.old,
    chapters: 3,
    order: 33,
  ),
  BibleBook(
    id: 'habakkuk',
    name: 'Habakkuk',
    abbreviation: 'Hab',
    testament: Testament.old,
    chapters: 3,
    order: 34,
  ),
  BibleBook(
    id: 'zephaniah',
    name: 'Zephaniah',
    abbreviation: 'Zeph',
    testament: Testament.old,
    chapters: 3,
    order: 35,
  ),
  BibleBook(
    id: 'haggai',
    name: 'Haggai',
    abbreviation: 'Hag',
    testament: Testament.old,
    chapters: 2,
    order: 36,
  ),
  BibleBook(
    id: 'zechariah',
    name: 'Zechariah',
    abbreviation: 'Zech',
    testament: Testament.old,
    chapters: 14,
    order: 37,
  ),
  BibleBook(
    id: 'malachi',
    name: 'Malachi',
    abbreviation: 'Mal',
    testament: Testament.old,
    chapters: 4,
    order: 38,
  ),
  BibleBook(
    id: 'matthew',
    name: 'Matthew',
    abbreviation: 'Matt',
    testament: Testament.newT,
    chapters: 28,
    order: 39,
  ),
  BibleBook(
    id: 'mark',
    name: 'Mark',
    abbreviation: 'Mark',
    testament: Testament.newT,
    chapters: 16,
    order: 40,
  ),
  BibleBook(
    id: 'luke',
    name: 'Luke',
    abbreviation: 'Luke',
    testament: Testament.newT,
    chapters: 24,
    order: 41,
  ),
  BibleBook(
    id: 'john',
    name: 'John',
    abbreviation: 'John',
    testament: Testament.newT,
    chapters: 21,
    order: 42,
  ),
  BibleBook(
    id: 'acts',
    name: 'Acts',
    abbreviation: 'Acts',
    testament: Testament.newT,
    chapters: 28,
    order: 43,
  ),
  BibleBook(
    id: 'romans',
    name: 'Romans',
    abbreviation: 'Rom',
    testament: Testament.newT,
    chapters: 16,
    order: 44,
  ),
  BibleBook(
    id: '1_corinthians',
    name: '1 Corinthians',
    abbreviation: '1 Cor',
    testament: Testament.newT,
    chapters: 16,
    order: 45,
  ),
  BibleBook(
    id: '2_corinthians',
    name: '2 Corinthians',
    abbreviation: '2 Cor',
    testament: Testament.newT,
    chapters: 13,
    order: 46,
  ),
  BibleBook(
    id: 'galatians',
    name: 'Galatians',
    abbreviation: 'Gal',
    testament: Testament.newT,
    chapters: 6,
    order: 47,
  ),
  BibleBook(
    id: 'ephesians',
    name: 'Ephesians',
    abbreviation: 'Eph',
    testament: Testament.newT,
    chapters: 6,
    order: 48,
  ),
  BibleBook(
    id: 'philippians',
    name: 'Philippians',
    abbreviation: 'Phil',
    testament: Testament.newT,
    chapters: 4,
    order: 49,
  ),
  BibleBook(
    id: 'colossians',
    name: 'Colossians',
    abbreviation: 'Col',
    testament: Testament.newT,
    chapters: 4,
    order: 50,
  ),
  BibleBook(
    id: '1_thessalonians',
    name: '1 Thessalonians',
    abbreviation: '1 Thess',
    testament: Testament.newT,
    chapters: 5,
    order: 51,
  ),
  BibleBook(
    id: '2_thessalonians',
    name: '2 Thessalonians',
    abbreviation: '2 Thess',
    testament: Testament.newT,
    chapters: 3,
    order: 52,
  ),
  BibleBook(
    id: '1_timothy',
    name: '1 Timothy',
    abbreviation: '1 Tim',
    testament: Testament.newT,
    chapters: 6,
    order: 53,
  ),
  BibleBook(
    id: '2_timothy',
    name: '2 Timothy',
    abbreviation: '2 Tim',
    testament: Testament.newT,
    chapters: 4,
    order: 54,
  ),
  BibleBook(
    id: 'titus',
    name: 'Titus',
    abbreviation: 'Titus',
    testament: Testament.newT,
    chapters: 3,
    order: 55,
  ),
  BibleBook(
    id: 'philemon',
    name: 'Philemon',
    abbreviation: 'Phlm',
    testament: Testament.newT,
    chapters: 1,
    order: 56,
  ),
  BibleBook(
    id: 'hebrews',
    name: 'Hebrews',
    abbreviation: 'Heb',
    testament: Testament.newT,
    chapters: 13,
    order: 57,
  ),
  BibleBook(
    id: 'james',
    name: 'James',
    abbreviation: 'Jas',
    testament: Testament.newT,
    chapters: 5,
    order: 58,
  ),
  BibleBook(
    id: '1_peter',
    name: '1 Peter',
    abbreviation: '1 Pet',
    testament: Testament.newT,
    chapters: 5,
    order: 59,
  ),
  BibleBook(
    id: '2_peter',
    name: '2 Peter',
    abbreviation: '2 Pet',
    testament: Testament.newT,
    chapters: 3,
    order: 60,
  ),
  BibleBook(
    id: '1_john',
    name: '1 John',
    abbreviation: '1 John',
    testament: Testament.newT,
    chapters: 5,
    order: 61,
  ),
  BibleBook(
    id: '2_john',
    name: '2 John',
    abbreviation: '2 John',
    testament: Testament.newT,
    chapters: 1,
    order: 62,
  ),
  BibleBook(
    id: '3_john',
    name: '3 John',
    abbreviation: '3 John',
    testament: Testament.newT,
    chapters: 1,
    order: 63,
  ),
  BibleBook(
    id: 'jude',
    name: 'Jude',
    abbreviation: 'Jude',
    testament: Testament.newT,
    chapters: 1,
    order: 64,
  ),
  BibleBook(
    id: 'revelation',
    name: 'Revelation',
    abbreviation: 'Rev',
    testament: Testament.newT,
    chapters: 22,
    order: 65,
  ),
];

/// 929 Old Testament + 260 New Testament.
const int kTotalChapters = 1189;

final Map<String, BibleBook> _byId = {for (final b in kBibleBooks) b.id: b};

/// Look a book up by [BibleBook.id]. Throws on an unknown id: ids are static
/// data, so an unknown one is a programming error, not user input.
BibleBook bookById(String id) =>
    _byId[id] ?? (throw ArgumentError.value(id, 'id', 'unknown Bible book'));

Iterable<BibleBook> booksIn(Testament t) =>
    kBibleBooks.where((b) => b.testament == t);
